---
# tasks file for installing_docker
- name: Update apt packeges
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Verify fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
- name: Set up the repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker
    update_cache: yes

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot
