---
# tasks file for running_docker_containers
- name: pull docker image
  docker_image:
    name: httpd
    source: pull

- name: Up container with apache
  shell: "docker run -dit --name my-apache-app -p 8080:80"
